name: Lint Code Base

on:
  push: 
    branches: [main]

jobs:
  build:

    name: Lint Code Base

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codee
        uses: actions/checkout@v2
        with:

          fetch-depth: 0


      - name: Linter Exectiton
        uses: github/super-linter@v4
        env: 

          DEFAULT_BRANCH: main
          GITHUB_TOKEN: token
          LINTER:RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE : .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true