name: Prueba Linter
on: [push]
jobs:
  Linter-test:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies 
        run: npm install
      
      - name: Run Lint
        run: npm run lint

  Cypress-test:
    runs-on: ubuntu-latest
    needs: linter-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Cypress ejecutar
        id: cypress
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Guardar result
        run: echo ${{ steps.cypress.outcome}} > result.txt

      - name: Actualizar result
        uses: actions/upload-artifact@v2
        with:
          name: result.txt
          path: result.txt

  Add_badge_job:
    runs-on: ubuntu-latest
    if: ${{always()}}
    needs: Cypress-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: result.txt
    - name: output-artifact
      run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
    - name: Action Update Readme
      uses: ./.github/actions/badge/
      with:
        resultado_test: ${{ steps.cypress.outputs.cypress_outcome }}
    - name: Push cambios Readme
      run: |
        git config user.name abmataix5
        git config user.email mataix.ab@gmail.com
        git add .
        git commit --allow-empty -m "Actualizar readme"
        git push 

  deploy:
    runs-on: ubuntu-latest
    needs: Cypress-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Desplegar App en vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.TOKEN_GITHUB }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./