name: Prueba Linter
on: [push]
jobs:
  Linter-test:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies 
        run: npm install
      
      - name: Run Lint
        run: npm run lint

  Cypress-test:
    runs-on: ubuntu-latest
    needs: linter-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Cypress ejecutar
        id: cypress
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Guardar result
        run: echo ${{ steps.cypress.outcome}} > result.txt

      - name: Actualizar result
        uses: actions/upload-artifact@v2
        with:
          name: result.txt
          path: result.txt